In [15]:
import os
import pandas as pd

In [16]:
!export GOOGLE_APPLICATION_CREDENTIALS="/Users/hansel/hackathon/2019/nuveen/Hackathon2019-Nuveen-31af23960028.json"

In [22]:
GOOGLE_APPLICATION_CREDENTIALS="/Users/hansel/hackathon/2019/nuveen/Hackathon2019-Nuveen-31af23960028.json"

In [17]:
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    "/Users/hansel/hackathon/2019/nuveen/Hackathon2019-Nuveen-31af23960028.json")

scoped_credentials = credentials.with_scopes(
    ['https://www.googleapis.com/auth/cloud-platform'])

In [18]:
from google.cloud import bigquery

In [23]:
credentials = service_account.Credentials.from_service_account_file(
    GOOGLE_APPLICATION_CREDENTIALS,
    scopes=["https://www.googleapis.com/auth/cloud-platform"],
)

In [24]:
client = bigquery.Client(
    credentials=credentials,
    project="hackathon2019-nuveen",
)

In [28]:
query = """
   SELECT *  FROM `hackathon2019-nuveen.NuveenDataset.NuveenEvents` LIMIT 10;
"""

In [29]:
query_job = client.query(query)

In [30]:
print("The query data:")



for row in query_job:
    # Row values can be accessed by field name or index.
    print("name={}, count={}".format(row["GLOBALEVENTID"], row["SQLDATE"], row["MonthYear"], row["Year"], row["FractionDate"], row["Actor1Code"], row["Actor1Name"], row["Actor1CountryCode"], row["Actor1KnownGroupCode"], row["Actor1EthnicCode"], row["Actor1Religion1Code"], row["Actor1Religion2Code"], row["Actor1Type1Code"], row["Actor1Type2Code"], row["Actor1Type3Code"], row["Actor2Code"], row["Actor2Name"], row["Actor2CountryCode"], row["Actor2KnownGroupCode"], row["Actor2EthnicCode"], row["Actor2Religion1Code"], row["Actor2Religion2Code"], row["Actor2Type1Code"], row["Actor2Type2Code"], row["Actor2Type3Code"], row["IsRootEvent"], row["EventCode"], row["EventBaseCode"], row["EventRootCode"], row["QuadClass"], row["GoldsteinScale"], row["NumMentions"], row["NumSources"], row["NumArticles"], row["AvgTone"], row["Actor1Geo_Type"], row["Actor1Geo_FullName"], row["Actor1Geo_CountryCode"], row["Actor1Geo_ADM1Code"], row["Actor1Geo_ADM2Code"], row["Actor1Geo_Lat"], row["Actor1Geo_Long"], row["Actor1Geo_FeatureID"], row["Actor2Geo_Type"], row["Actor2Geo_FullName"], row["Actor2Geo_CountryCode"], row["Actor2Geo_ADM1Code"], row["Actor2Geo_ADM2Code"], row["Actor2Geo_Lat"], row["Actor2Geo_Long"], row["Actor2Geo_FeatureID"], row["ActionGeo_Type"], row["ActionGeo_FullName"], row["ActionGeo_CountryCode"], row["ActionGeo_ADM1Code"], row["ActionGeo_ADM2Code"], row["ActionGeo_Lat"], row["ActionGeo_Long"], row["ActionGeo_FeatureID"], row["DATEADDED"], row["SOURCEURL"])

SyntaxError: unexpected EOF while parsing (<ipython-input-30-b5eadd7c8c54>, line 4)

In [48]:
df = (
    client.query(query).result().to_dataframe()
)
print(dataframe.head())

   GLOBALEVENTID   SQLDATE  MonthYear  Year  FractionDate Actor1Code  \
0      885133316  20191108     201911  2019     2019.8438        BUS
1      766702058  20180624     201806  2018     2018.4767     MNCUSA
2      884652345  20191106     201911  2019     2019.8384        MNC
3      701782209  20171028     201710  2017     2017.8164     MNCUSA
4      587995658  20161012     201610  2016     2016.7726        BUS

                   Actor1Name Actor1CountryCode Actor1KnownGroupCode  \
0                    BUSINESS              None                 None
1                   MICROSOFT               USA                 None
2  SHIP FINANCE INTERNATIONAL              None                 None
3          FTI CONSULTING INC               USA                 None
4                    BUSINESS              None                 None

  Actor1EthnicCode  ... ActionGeo_Type ActionGeo_FullName  \
0             None  ...              0               None
1             None  ...              0               None
2             None  ...              0               None
3             None  ...              0               None
4             None  ...              0               None

  ActionGeo_CountryCode ActionGeo_ADM1Code ActionGeo_ADM2Code ActionGeo_Lat  \
0                  None               None               None          None
1                  None               None               None          None
2                  None               None               None          None
3                  None               None               None          None
4                  None               None               None          None

  ActionGeo_Long ActionGeo_FeatureID       DATEADDED  \
0           None                None  20191108000000
1           None                None  20180624004500
2           None                None  20191106023000
3           None                None  20171028010000
4           None                None  20161012000000

                                           SOURCEURL
0  https://www.businessinsider.com/how-to-set-up-...
1  https://www.zdnet.com/article/microsoft-unexpe...
2  https://www.wkrb13.com/2019/11/06/ship-finance...
3  https://www.dailypolitical.com/2017/10/27/fti-...
4  http://www.business2community.com/human-resour...

[5 rows x 61 columns]

In [49]:
df

,GLOBALEVENTID,SQLDATE,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,...,ActionGeo_Type,ActionGeo_FullName,ActionGeo_CountryCode,ActionGeo_ADM1Code,ActionGeo_ADM2Code,ActionGeo_Lat,ActionGeo_Long,ActionGeo_FeatureID,DATEADDED,SOURCEURL
0,885133316,20191108,201911,2019,2019.8438,BUS,BUSINESS,None,None,None,...,0,None,None,None,None,None,None,None,20191108000000,https://www.businessinsider.com/how-to-set-up-...
1,766702058,20180624,201806,2018,2018.4767,MNCUSA,MICROSOFT,USA,None,None,...,0,None,None,None,None,None,None,None,20180624004500,https://www.zdnet.com/article/microsoft-unexpe...
2,884652345,20191106,201911,2019,2019.8384,MNC,SHIP FINANCE INTERNATIONAL,None,None,None,...,0,None,None,None,None,None,None,None,20191106023000,https://www.wkrb13.com/2019/11/06/ship-finance...
3,701782209,20171028,201710,2017,2017.8164,MNCUSA,FTI CONSULTING INC,USA,None,None,...,0,None,None,None,None,None,None,None,20171028010000,https://www.dailypolitical.com/2017/10/27/fti-...
4,587995658,20161012,201610,2016,2016.7726,BUS,BUSINESS,None,None,None,...,0,None,None,None,None,None,None,None,20161012000000,http://www.business2community.com/human-resour...
5,880912857,20191020,201910,2019,2019.7945,BUS,COMPANY,None,None,None,...,0,None,None,None,None,None,None,None,20191020000000,https://www.wkrb13.com/2019/10/19/1-65-earning...
6,884375623,20191105,201911,2019,2019.8356,BUS,INDUSTRY,None,None,None,...,0,None,None,None,None,None,None,None,20191105003000,https://news.yahoo.com/twistles-16-million-fin...
7,880321598,20191017,201910,2019,2019.7863,MNCUSAHLH,ABBOTT LABORATORIES,USA,None,None,...,0,None,None,None,None,None,None,None,20191017101500,https://www.wkrb13.com/2019/10/17/cerebellum-g...
8,847457350,20190524,201905,2019,2019.3945,BUS,COMPANY,None,None,None,...,0,None,None,None,None,None,None,None,20190524001500,https://news.yahoo.com/institutions-own-grange...
9,678487772,20170804,201708,2017,2017.5863,BUS,COMPANIES,None,None,None,...,0,None,None,None,None,None,None,None,20170804000000,http://www.crainsdetroit.com/article/20170803/...